spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/tf_funding?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      #dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8085

    #eureka:
    #client:
    #serviceUrl:
  #defaultZone: http://localhost:8761/eureka/