spring:
  application:
    name: authenticate-service
  datasource:
    url: jdbc:mysql://localhost/authdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8083

jwt:
  secret: secretkey123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/